import React, { useState, useEffect } from "react";

var GOLD = "#E8B931";
var DARK = "#0f0f1a";
var PASSWORD = "dvir1971";
var SUPA_URL = "https://qoswnccfcpzrzesdhuky.supabase.co";
var SUPA_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvc3duY2NmY3B6cnplc2RodWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMTMyMTcsImV4cCI6MjA4OTU4OTIxN30.MziqUUUzfInwgojcRyqqZgsKSt1a0MZ1uHUSqXf-lus";

function supaFetch(method, body) {
  var opts = { method: method, headers: { "apikey": SUPA_KEY, "Authorization": "Bearer " + SUPA_KEY, "Content-Type": "application/json", "Prefer": "return=representation" } };
  if (body) opts.body = JSON.stringify(body);
  return fetch(SUPA_URL + "/rest/v1/workshop_state?id=eq.current", opts).then(function(r) { return r.json(); });
}
function getState() { return supaFetch("GET"); }
function setState(sid, si) { return supaFetch("PATCH", { session_id: sid, slide_index: si, updated_at: new Date().toISOString() }); }

/* ===== COMPONENTS ===== */
function Txt(p) {
  return React.createElement("div", { style: { fontSize: p.size || 16, fontWeight: p.bold ? 700 : 400, color: p.color || "#fff", textAlign: p.center ? "center" : "right", direction: "rtl", lineHeight: 1.7, whiteSpace: "pre-line" } }, p.children);
}
function CenterSlide(p) {
  return React.createElement("div", { style: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100%", gap: p.gap || 16, padding: "0 8px" } }, p.children);
}
function Slide(p) {
  return React.createElement("div", { style: { display: "flex", flexDirection: "column", height: "100%", direction: "rtl", gap: p.gap || 0, padding: "0 4px", overflow: "auto" } }, p.children);
}
function GoldBox(p) {
  return React.createElement("div", { style: { background: p.bg || "rgba(232,185,49,0.08)", border: "1px solid " + (p.border || "rgba(232,185,49,0.2)"), borderRadius: 12, padding: p.pad || 14 } }, p.children);
}
function Badge() { return React.createElement("div", { style: { fontSize: 16, color: GOLD, letterSpacing: 3, fontWeight: 700 } }, "COMAX × AI"); }
function Divider() { return React.createElement("div", { style: { width: 60, height: 3, background: "linear-gradient(90deg," + GOLD + ",#F7D060)", borderRadius: 2 } }); }

/* ===== SLIDE BUILDERS ===== */
function titleSlide(num, total, title, sub) {
  return React.createElement(CenterSlide, { gap: 16 }, React.createElement(Badge), React.createElement(Txt, { size: 32, bold: true, center: true }, "סדנת AI למכירות שטח"), React.createElement(Divider), React.createElement(Txt, { size: 18, color: "#ccc", center: true }, "מפגש " + num + " מתוך " + total), React.createElement(Txt, { size: 24, color: GOLD, bold: true, center: true }, title), React.createElement(Txt, { size: 13, color: "#999", center: true }, sub));
}
function closingSlide(next, emoji, footer) {
  return React.createElement(CenterSlide, { gap: 20 }, React.createElement(Badge), React.createElement(Txt, { size: 28, bold: true, center: true }, "נתראה בפעם הבאה!"), React.createElement(Divider), React.createElement(Txt, { size: 18, color: "#ccc", center: true }, next), React.createElement("div", { style: { fontSize: 40 } }, emoji), React.createElement(Txt, { size: 13, color: "#666", center: true }, footer));
}
function breakSlide(text) {
  return React.createElement(CenterSlide, { gap: 20 }, React.createElement("div", { style: { fontSize: 56 } }, "☕"), React.createElement(Txt, { size: 28, bold: true, color: GOLD, center: true }, "הפסקה – 10 דקות"), React.createElement(Txt, { size: 16, color: "#aaa", center: true }, text));
}
function quoteSlide(html, footer) {
  return React.createElement(CenterSlide, { gap: 20 }, React.createElement(Txt, { size: 40, color: "rgba(232,185,49,0.3)", center: true }, '"'), React.createElement("div", { style: { fontSize: 22, fontWeight: 700, color: "#fff", textAlign: "center", lineHeight: 1.6, maxWidth: 500 }, dangerouslySetInnerHTML: { __html: html } }), React.createElement(Txt, { size: 40, color: "rgba(232,185,49,0.3)", center: true }, '"'), React.createElement(Txt, { size: 13, color: "#888", center: true }, footer));
}
function codeSlide(title, code, footer) {
  return React.createElement(Slide, null, React.createElement(Txt, { size: 20, bold: true, color: GOLD }, title), React.createElement("div", { style: { background: "#1a1a2e", borderRadius: 12, padding: 14, flex: 1, fontFamily: "monospace", border: "1px solid #333", marginTop: 8, overflow: "auto" } }, React.createElement(Txt, { size: 12, color: GOLD }, "PROMPT:"), React.createElement(Txt, { size: 12, color: "#ddd" }, code)), footer ? React.createElement(Txt, { size: 11, color: "#888", center: true }, footer) : null);
}
function summarySlide(items, hw) {
  return React.createElement(Slide, null, React.createElement(Txt, { size: 22, bold: true, color: GOLD }, "🎯 מה לוקחים הביתה?"), React.createElement("div", { style: { display: "flex", flexDirection: "column", gap: 6, margin: "10px 0" } }, items.map(function(x, i) { return React.createElement("div", { key: i, style: { display: "flex", gap: 10, alignItems: "center", background: "rgba(232,185,49,0.06)", borderRadius: 10, padding: "8px 12px", border: "1px solid rgba(232,185,49,0.15)" } }, React.createElement("div", { style: { fontSize: 20 } }, x[0]), React.createElement("div", { style: { flex: 1 } }, React.createElement(Txt, { size: 13, bold: true }, x[1]), React.createElement(Txt, { size: 11, color: "#aaa" }, x[2]))); })), React.createElement("div", { style: { background: "linear-gradient(135deg," + GOLD + ",#F7D060)", borderRadius: 12, padding: 12 } }, React.createElement("div", { style: { fontSize: 14, fontWeight: 800, color: "#1a1a2e", textAlign: "right", direction: "rtl" } }, "📌 משימה:"), React.createElement("div", { style: { fontSize: 13, color: "#1a1a2e", textAlign: "right", direction: "rtl", lineHeight: 1.7 } }, hw)));
}
function twoColSlide(title, lt, li, lc, rt, ri, rc) {
  function col(t, items, clr) { return React.createElement("div", { style: { flex: 1, background: clr + "18", border: "1px solid " + clr + "55", borderRadius: 14, padding: 14 } }, React.createElement(Txt, { size: 15, bold: true, color: clr }, t), React.createElement("div", { style: { marginTop: 8 } }, items.map(function(item, i) { return React.createElement(Txt, { key: i, size: 13, color: "#ddd" }, "• " + item); }))); }
  return React.createElement(Slide, null, React.createElement(Txt, { size: 22, bold: true, color: GOLD }, title), React.createElement("div", { style: { display: "flex", gap: 14, flex: 1, marginTop: 12 } }, col(lt, li, lc), col(rt, ri, rc)));
}

/* ========== SESSION 1: מהתחלה לפגישה ========== */
var S1 = [
  { c: titleSlide(1, 3, '"מהתחלה לפגישה"', "💡 שבירת חסמים • 5 כללי זהב • שרשרת הכנה • תוכנית פגישה/שיחה"), n: "\"בוקר טוב לכולם! אז הבוס אמר לכם שאתם הולכים לסדנת AI. אני בטוח שחלק חשבו 'יופי, עוד הרצאה שאני יכול לישון בה עם העיניים פתוחות'.\n\nאז יש לי חדשות: היום אף אחד לא ישן. למה? כי היום אנחנו לא מדברים על AI – אנחנו משתמשים ב-AI. על לקוחות אמיתיים שלכם. בזמן אמת. עם הטלפון שלכם.\n\nמי שעובד בשטח – נכין פגישה. מי שעובד בטלפון – נכין שיחה. לכולם יהיה כלי שעובד מחר בבוקר.\n\nואם בסוף המפגש לא תגידו 'רגע, זה באמת שימושי' – הקפה עליי. לא באמת, אבל נעים לדמיין.\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 24, bold: true, color: GOLD }, "מה בתוכנית היום?"), React.createElement("div", { style: { marginTop: 12 } }, [{ t: "15 דק׳", i: "👋", n: "פתיחה + סיבוב", d: "מה חושבים על AI?" }, { t: "10 דק׳", i: "🧠", n: "מה AI יכול ולא", d: "ציפיות ריאליות" }, { t: "20 דק׳", i: "🎪", n: "הדגמה חיה", d: "AI פוגש לקוח אמיתי" }, { t: "15 דק׳", i: "🏆", n: "5 כללי זהב", d: "איך לדבר עם AI" }, { t: "25 דק׳", i: "💪", n: "תרגיל", d: "הלקוח שלכם + שדרוג" }, { t: "10 דק׳", i: "☕", n: "הפסקה", d: "" }, { t: "20 דק׳", i: "⛓️", n: "שרשרת הכנה", d: "מחקר → כרטיס → תוכנית" }, { t: "25 דק׳", i: "⏱️", n: "תרגיל 5 דקות", d: "הכנה מלאה לפגישה/שיחה" }, { t: "10 דק׳", i: "🎯", n: "סיכום + משימה", d: "" }].map(function(x, i) { return React.createElement("div", { key: i, style: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } }, React.createElement("div", { style: { fontSize: 22 } }, x.i), React.createElement("div", { style: { flex: 1 } }, React.createElement("div", { style: { fontSize: 15, fontWeight: 700, color: "#fff", textAlign: "right" } }, x.n), x.d ? React.createElement("div", { style: { fontSize: 12, color: "#aaa", textAlign: "right" } }, x.d) : null), React.createElement("div", { style: { fontSize: 12, color: GOLD, fontWeight: 600 } }, x.t)); }))), n: "\"שעתיים וחצי. חצי ראשון: מה AI יכול, איך מדברים איתו, תרגיל ראשון. חצי שני: שרשרת הכנה מלאה לפגישה או שיחת טלפון.\n\nבסוף – תצאו עם כלי שעובד מחר בבוקר.\"" },
  { c: React.createElement(CenterSlide, null, React.createElement("div", { style: { fontSize: 56 } }, "🤔"), React.createElement(Txt, { size: 24, bold: true, color: GOLD, center: true }, "סיבוב פתיחה"), React.createElement(GoldBox, null, React.createElement(Txt, { size: 18 }, React.createElement("span", { style: { color: GOLD, fontWeight: 700 } }, "1."), " מה אתם חושבים על AI?"), React.createElement(Txt, { size: 18 }, React.createElement("span", { style: { color: GOLD, fontWeight: 700 } }, "2."), " מתי הרגשתם \"הלוואי שמישהו עוזר\"?")), React.createElement(Txt, { size: 13, color: "#888", center: true }, "⏱️ משפט אחד כל אחד – בלי נאומים!")), n: "\"טוב, לפני שנתחיל – סיבוב מהיר. כל אחד אומר שני דברים:\n1. מה הוא חושב על AI\n2. מתי בפעם האחרונה הרגיש 'הלוואי שמישהו עוזר'\n\nואני מדבר על עבודה, לא על להרכיב ארון מאיקאה.\n\n[30 שניות כל אחד. הגבילו. רשמו תשובות מעניינות על הלוח]\n\n[אחרי הסיבוב:]\n'מעולה. שמעתי פה כמה דברים: יש כאלה שחושבים AI זה העתיד, יש כאלה שחושבים שזה באזז, ויש מישהו שבטוח שהרובוטים יחליפו אותנו.\n\nחדשות: אף אחד לא טועה לגמרי. אבל בואו נבין מה באמת קורה.'\"" },
  { c: twoColSlide("מה AI יכול ומה לא", "✅ AI מעולה ב:", ["לנסח טקסטים ומיילים", "לחקור ענף מזון/אופנה תוך שניות", "רעיונות לגישת מכירה", "תרגול התנגדויות (Roleplay)", "לסכם שיחה טלפונית", "לעבוד 24/7 בלי קפה"], "#4CAF50", "❌ AI גרוע ב:", ["לבנות יחסים אישיים", "להרגיש טון בטלפון", "אינטואיציה של סוכן מנוסה", "לקפוץ ללקוח לביקור", "לסגור עסקה בלחיצת יד", "לדעת שדני מרוגז כי ריבו עם אשתו"], "#F44336"), n: "\"בואו נשים את הדברים על השולחן. AI זה לא ג'יימס בונד של מכירות. הוא לא הולך לסגור לכם עסקאות, לא הולך להתקשר ללקוח במקומכם, לא הולך לשבת עם בעל מסעדה לאכול חומוס.\n\n[הצביעו על הצד הירוק]\n'אבל תראו מה הוא כן יכול: לנסח, לחקור, לתרגל, לסכם. בעצם – הוא עושה את כל העבודה המשעממת שאתם לא אוהבים לעשות.'\n\n[הצביעו על הצד האדום]\n'ומה הוא לא יכול? בדיוק את מה שאתם הכי טובים בו: לבנות קשר, להרגיש בן אדם, לדעת מתי ללחוץ ומתי לעזוב.'\n\n'אז המשוואה פשוטה: AI עושה את ההכנה. אתם עושים את הקסם. ביחד – אתם בלתי ניתנים לעצירה.'\"" },
  { c: twoColSlide("🤖 AI לעומת אוטומציה – מה ההבדל?", "⚙️ אוטומציה:", ["עושה פעולה קבועה שהגדרת מראש", "אם X קורה → עשה Y", "דוגמה: שליחת SMS אוטומטי ללקוח", "דוגמה: דוח שנשלח כל יום ראשון", "לא 'חושב' – מבצע הוראות", "מדויק אבל טיפש"], "#4FC3F7", "🧠 AI (בינה מלאכותית):", ["חושב, מנתח, יוצר תוכן חדש", "מבין שפה טבעית ומגיב", "דוגמה: כותב הודעה מותאמת ללקוח", "דוגמה: מנתח למה לקוח התנגד", "מבין הקשר ומתאים תשובה", "יצירתי אבל לפעמים טועה"], GOLD), n: "\"עכשיו, לפני שממשיכים – בואו נבין הבדל חשוב. הרבה אנשים מבלבלים בין AI לאוטומציה.\n\nאוטומציה זה כמו מכונת קפה – לוחצים כפתור, יוצא קפה. תמיד אותו קפה. זה כלי כמו Make, Zapier, תהליכים אוטומטיים ב-CRM. מעולה, אבל לא חושב.\n\nAI זה כמו בריסטה – אתם אומרים לו 'אני רוצה משהו חזק אבל לא מר' והוא מכין משהו מותאם. הוא מבין שפה, מנתח מצב, ויוצר תשובה חדשה כל פעם.\n\nבסדנה הזו אנחנו עובדים עם AI – עם כלים שמבינים מה אתם רוצים ועוזרים לכם לחשוב, לנסח, ולהתכונן. לא אוטומציה שרצה ברקע.\n\nאגב – שניהם חשובים! אוטומציה חוסכת זמן על דברים חוזרים. AI עוזר לכם לחשוב ולכתוב טוב יותר. אידיאלית – משתמשים בשניהם.'\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 20, bold: true, color: GOLD }, "🔧 כלי AI מרכזיים – מה ההבדלים?"), React.createElement("div", { style: { display: "flex", flexDirection: "column", gap: 6, flex: 1, marginTop: 10 } }, [{ n: "ChatGPT", co: "OpenAI", d: "הכי מוכר. טוב לשיחה, כתיבה, רעיונות. חינם (גרסת 4o). גרסת Plus = חזק יותר.", c: "#4CAF50", r: "⭐ מומלץ להתחלה" }, { n: "Claude", co: "Anthropic", d: "מצוין לטקסטים ארוכים, ניתוח, הבנת הקשר. מדויק יותר בעברית. חינם.", c: "#9C27B0", r: "⭐ מומלץ לכתיבה" }, { n: "Gemini", co: "Google", d: "משולב בגוגל. טוב למחקר ולחיפוש מידע עדכני. חינם.", c: "#4FC3F7", r: "טוב למחקר" }, { n: "Copilot", co: "Microsoft", d: "משולב ב-Edge וב-Office. טוב למיילים ומסמכים. חינם.", c: "#F7D060", r: "טוב למיילים" }, { n: "Claude Code", co: "Anthropic", d: "לפיתוח תוכנה ואפליקציות. לא רלוונטי לסוכני מכירות.", c: "#666", r: "למפתחים" }].map(function(x, i) { return React.createElement("div", { key: i, style: { display: "flex", gap: 10, alignItems: "center", background: "rgba(255,255,255,0.03)", borderRadius: 8, padding: "8px 12px", border: "1px solid #2a2a4a" } }, React.createElement("div", { style: { minWidth: 70 } }, React.createElement(Txt, { size: 14, bold: true, color: x.c }, x.n), React.createElement(Txt, { size: 10, color: "#666" }, x.co)), React.createElement("div", { style: { flex: 1 } }, React.createElement(Txt, { size: 12, color: "#ccc" }, x.d)), React.createElement(Txt, { size: 10, color: x.c }, x.r)); })), React.createElement(GoldBox, { pad: 10 }, React.createElement(Txt, { size: 13, color: GOLD, bold: true, center: true }, "💡 לסדנה: ChatGPT או Claude. התקינו עכשיו!"))), n: "\"עכשיו, כלי AI – יש הרבה ואנשים מתבלבלים. בואו נעשה סדר:\n\nChatGPT – של OpenAI. הכי מוכר בעולם. הורידו את האפליקציה, יש גרסה חינמית מעולה. טוב לשיחה, לרעיונות, לכתיבה.\n\nClaude – של Anthropic. זה מה שאנחנו יושבים בו עכשיו. מצוין לטקסטים ארוכים, מדויק בעברית, טוב מאוד לניתוח. גם חינם.\n\nGemini – של Google. מחובר לגוגל אז טוב למחקר ולמידע עדכני. אם רוצים לחקור לקוח – שווה.\n\nCopilot – של Microsoft. משולב ב-Outlook ו-Office. אם אתם כותבים הרבה מיילים – שווה.\n\nClaude Code – זה לתכנות, לא רלוונטי לכם. אם מישהו שואל – זה כלי למפתחים.\n\n[חשוב:]\n'לסדנה שלנו – ChatGPT או Claude. שניהם חינם, שניהם מעולים. מי שעדיין לא התקין – עכשיו! תפתחו App Store או Google Play, תחפשו ChatGPT או Claude, ותתקינו. דקה אחת. אני מחכה.'\n\n[תנו דקה-שתיים להתקנה]\"" },
  { c: quoteSlide("AI לא יחליף סוכן מכירות.<br/><span style='color:" + GOLD + "'>סוכן שמשתמש ב-AI</span><br/>יחליף סוכן שלא.", "(ואל תגידו שלא הזהרנו 😏)"), n: "[השאירו את השקף 5 שניות בשקט. תנו לקהל לקרוא.]\n\n\"קראו את זה. תזכרו את זה.\n\nזה לא איום – זה הזדמנות. הסוכנים שילמדו להשתמש ב-AI לפני כולם? הם אלה שיסגרו יותר עסקאות, יבזבזו פחות זמן, ויגיעו לפגישות מוכנים.\n\nועכשיו, בואו נפסיק לדבר ונראה את זה בפעולה. מי רוצה להתנדב?\"" },
  { c: React.createElement(CenterSlide, null, React.createElement("div", { style: { fontSize: 56 } }, "🎪"), React.createElement(Txt, { size: 28, bold: true, color: GOLD, center: true }, "הדגמה חיה"), React.createElement(GoldBox, null, React.createElement(Txt, { size: 16 }, React.createElement("span", { style: { color: GOLD } }, "המשימה:"), " ספרו על הלקוח הכי קשה. שני משפטים."), React.createElement(Txt, { size: 16 }, React.createElement("span", { style: { color: GOLD } }, "אני:"), " אכניס ל-AI בזמן אמת."), React.createElement(Txt, { size: 16 }, React.createElement("span", { style: { color: GOLD } }, "ביחד:"), " נראה מה יוצא.")), React.createElement(Txt, { size: 13, color: "#888", center: true }, "🎤 הביישן מתנדב ראשון!")), n: "\"אוקיי, הגיע הרגע. אני צריך מתנדב. מישהו שיש לו לקוח שמעצבן אותו.\n\n[אם אף אחד לא מתנדב:]\n'טוב, מי שלא מתנדב – AI ימליץ לי על שאלות להתנגדויות שלו בכל מקרה, אז עדיף שתשלטו בתהליך.'\n\n[כשמישהו מתנדב:]\n'מעולה! ספר לנו: מי הלקוח, מה הוא עושה, ולמה הוא מסובך? שני משפטים, כאילו אתה מספר לחבר בהפסקת קפה.'\n\n'בעל מיני? חנות בגדים? רשת? מישהו שאתם מנסים להשיג בטלפון?'\n\n[הקלד את הפרומפט בזמן אמת על המסך הגדול – תנו לכולם לראות את התהליך]\"" },
  { c: codeSlide("🖥️ הפרומפט שמקליד:", "אתה יועץ מכירות מומחה ERP/POS\nלקמעונאות מזון ואופנה.\n\nלקוח: [בעל מיניסופר 2 סניפים, קופה ישנה,\nמתלונן על חוסר שליטה במלאי]\n\nתן לי:\n1. שלוש שאלות חכמות שיגרמו לחשוב מחדש\n2. שני כאבים שכנראה יש לו ולא מודע\n3. משפט פתיחה – לפגישה פיזית או לשיחת טלפון", "💡 תפקיד → הקשר → משימה → פורמט"), n: "\"לא 'עזור לי למכור'. תפקיד, הקשר, משימה ברורה.\n\n[הרץ, הצג] 'רלוונטי?'\n\n[פרומפט המשך:] 'גישה אחרת – מבוססת סיפור לקוח דומה.'\"" },
  { c: twoColSlide("5 כללי הזהב", "✅ עשו:", ["1️⃣ תפקיד – 'אתה מומחה POS'", "2️⃣ הקשר – 'רשת ביגוד, 3 סניפים'", "3️⃣ משימה – '3 שאלות פתיחה'", "4️⃣ פורמט – 'כהודעת WhatsApp'", "5️⃣ חזרו ושפרו – 'יותר ישיר'"], "#4CAF50", "❌ אל תעשו:", ["'עזור לי למכור'", "'יש לי לקוח'", "'תכתוב משהו'", "'עזור לי עם הפגישה'", "לקחת תשובה ראשונה ולרוץ"], "#F44336"), n: "\"5 כללים. פשוטים. בואו.\n\nכלל 1: תנו תפקיד. כמו שנותנים תדריך לעובד חדש – 'אתה מומחה POS, 15 שנות ניסיון, הלקוח צריך פתרון למלאי'.\n\nכלל 2: תנו הקשר. AI לא קורא מחשבות. 'יש לי לקוח' = תשובה גנרית. 'רשת 5 חנויות אופנה, עובדת עם אקסלים, שוקלת מערכת' = עכשיו מדברים.\n\nכלל 3: משימה ברורה. לא 'עזור לי' – '3 שאלות פתיחה שלא נשמעות מכירתיות'.\n\nכלל 4: פורמט. רוצים WhatsApp? תגידו. מייל? תגידו. 3 נקודות? תגידו.\n\nכלל 5 – הכי חשוב: חזרו ושפרו! הפרומפט הראשון הוא טיוטה. אף אחד לא שולח הצעת מחיר בטיוטה ראשונה. 'תהיה יותר ישיר', 'תקצר', 'תנסה גישה הפוכה'.\n\nובונוס: AI לא נעלב! אפשר להגיד 'זה היה גרוע, תנסה שוב' והוא יגיד 'בטח!' – תנסו את זה עם השותף שלכם...\"" },
  { c: codeSlide("💪 תרגיל: הלקוח שלכם", "אני סוכן/ת Comax – ERP וקופות POS\nלקמעונאות מזון ואופנה.\n\nהלקוח: [בעל מיני 3 סניפים / בעלת בוטיק / רשת]\nהאתגר: [לא עונה / אומר יקר / יש מתחרה / חתום]\n\nעזור לי עם:\n1. שלוש שאלות פתיחה (לפגישה או טלפון)\n2. שתי נקודות כאב שלא מודע אליהן\n3. הצעה לפתיחת השיחה", "5 דק׳ כתבו → 10 דק׳ בזוגות → 5 דק׳ שיתוף"), n: "\"עכשיו תורכם! תוציאו טלפונים – כן, רשות רשמית.\n\n[הציגו את התבנית]\n\n'חשבו על לקוח אמיתי. לא דמיוני – אמיתי. מישהו שתפגשו בימים הקרובים, או שתתקשרו אליו. או מישהו שאיבדתם.\n\nגם מי שעובד בטלפון – תכתבו על לקוח שמתכננים להתקשר אליו.'\n\n[5 דקות עבודה עצמאית]\n\n[אם מישהו תקוע:] 'אל תסתבכו. פשוט כתבו: יש לי בעל מיני שאומר שיקר לו. מה אני עושה? – גם ככה יעבוד.'\n\n[אחרי 5 דקות:]\n'עכשיו פנו לשכן. תראו לו מה קיבלתם. הוא יראה לכם. פידבק אחד: מה חזק, מה חסר?'\n\n[אחרי 10 דקות:]\n'מי קיבל משהו שהפתיע אותו? מי מוכן לשתף?'\n\n[בחרו 2-3 מתנדבים, 2 דקות כל אחד]\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 20, bold: true, color: GOLD }, "🔥 שדרגו את הפרומפט"), React.createElement("div", { style: { background: "rgba(244,67,54,0.1)", borderRadius: 12, padding: 14, margin: "10px 0", border: "1px solid rgba(244,67,54,0.3)" } }, React.createElement(Txt, { size: 13, color: "#F44336", bold: true }, "❌ לפני:"), React.createElement(Txt, { size: 18, color: "#ddd" }, "\"תכתוב לי מייל ללקוח\"")), React.createElement(Txt, { size: 14, color: GOLD }, "⬇️ נוסיף ביחד: תפקיד, הקשר, משימה, פורמט..."), React.createElement("div", { style: { background: "rgba(76,175,80,0.1)", borderRadius: 12, padding: 14, border: "1px solid rgba(76,175,80,0.3)", flex: 1, display: "flex", alignItems: "center", justifyContent: "center", marginTop: 8 } }, React.createElement(Txt, { size: 16, color: "#4CAF50", center: true }, "✅ אחרי: נבנה ביחד בזמן אמת!"))), n: "\"'תכתוב מייל ללקוח' – למה גרוע? [קהל]\n\nבואו נתקן ביחד. [בנו בזמן אמת]\n\nעכשיו שדרגו את הפרומפט מהתרגיל. 5 דקות.\"" },
  { c: breakSlide("קפה, שירותים, ולבדוק אם AI עונה בלי Wi-Fi (ספוילר: לא)"), n: "\"הפסקה! 10 דקות. קחו קפה.\n\nואם רוצים להתמכר – תנסו עוד פרומפט על לקוח אחר.\n\nאחרי ההפסקה עולים רמה: שרשרת פרומפטים. לא פרומפט אחד – תהליך שלם של הכנה לפגישה ב-5 דקות.\"" },
  { c: React.createElement(CenterSlide, null, React.createElement(Txt, { size: 22, bold: true, color: GOLD, center: true }, "עולים רמה: שרשרת פרומפטים"), React.createElement("div", { style: { display: "flex", gap: 24, marginTop: 12 } }, React.createElement("div", { style: { background: "rgba(255,255,255,0.05)", borderRadius: 14, padding: "18px 22px", border: "1px solid #333", textAlign: "center" } }, React.createElement("div", { style: { fontSize: 36 } }, "📝"), React.createElement(Txt, { size: 14, color: "#aaa", center: true, bold: true }, "לפני ההפסקה"), React.createElement(Txt, { size: 12, color: "#666", center: true }, "פרומפט בודד")), React.createElement("div", { style: { fontSize: 28, color: GOLD, display: "flex", alignItems: "center" } }, "→"), React.createElement("div", { style: { background: "rgba(232,185,49,0.1)", borderRadius: 14, padding: "18px 22px", border: "1px solid rgba(232,185,49,0.3)", textAlign: "center", boxShadow: "0 0 20px rgba(232,185,49,0.1)" } }, React.createElement("div", { style: { fontSize: 36 } }, "⛓️"), React.createElement(Txt, { size: 14, color: GOLD, center: true, bold: true }, "עכשיו"), React.createElement(Txt, { size: 12, color: "#ccc", center: true }, "שרשרת 3 פרומפטים"))), React.createElement(Txt, { size: 14, color: "#888", center: true }, "כל פרומפט מזין את הבא. 3 צעדים = הכנה מלאה ב-5 דקות.")), n: "\"לפני ההפסקה: פרומפט אחד. עכשיו: שרשרת של 3. באותה שיחה.\n\nמחקר → כרטיס → תוכנית. 5 דקות. למי שנכנס לפגישה 'ברגשת בטן' – זה נגמר היום.\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 22, bold: true, color: GOLD }, "⏱️ שיטת 5 הדקות"), React.createElement("div", { style: { display: "flex", flexDirection: "column", gap: 10, flex: 1, marginTop: 12 } }, [{ s: "1", t: "60 שנ׳", n: "🔍 מחקר ענפי", d: "אתגרים, כאבים, שפה ענפית", c: "#4FC3F7" }, { s: "2", t: "90 שנ׳", n: "📋 כרטיס לקוח", d: "הזדמנות, כאבים, שאלות, התנגדויות", c: GOLD }, { s: "3", t: "90 שנ׳", n: "🗺️ תוכנית פגישה/שיחה", d: "פתיחה → גילוי → ערך → סגירה", c: "#4CAF50" }].map(function(x, i) { return React.createElement("div", { key: i, style: { display: "flex", gap: 14 } }, React.createElement("div", { style: { width: 36, height: 36, borderRadius: 18, background: x.c, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, fontWeight: 800, color: "#1a1a2e", flexShrink: 0 } }, x.s), React.createElement("div", { style: { flex: 1, background: "rgba(255,255,255,0.03)", borderRadius: 10, padding: "10px 14px", border: "1px solid " + x.c + "33" } }, React.createElement(Txt, { size: 16, bold: true }, x.n), React.createElement(Txt, { size: 12, color: "#aaa" }, x.d), React.createElement(Txt, { size: 12, color: x.c, bold: true }, x.t))); })), React.createElement("div", { style: { background: "rgba(232,185,49,0.08)", borderRadius: 10, padding: 10, textAlign: "center", marginTop: 6 } }, React.createElement("span", { style: { color: "#aaa", fontSize: 13 } }, "+ דקה לקריאה = "), React.createElement("span", { style: { color: GOLD, fontSize: 16, fontWeight: 800 } }, "פחות מ-5 דקות"))), n: "\"3 שלבים. 5 דקות. באותה שיחה.\n\nשלב 1: מחקר – דקה. מה האתגרים של הענף.\nשלב 2: כרטיס – דקה וחצי. הזדמנויות, כאבים, שאלות.\nשלב 3: תוכנית – דקה וחצי. תסריט 30 דקות או 10 דקות טלפון.\"" },
  { c: codeSlide("🔍 שלב 1: מחקר ענפי", "אני סוכן Comax – ERP וקופות POS.\n\nמחר [פגישה/שיחה] עם בעלים של\n[מיניסופר 3 סניפים / חנות אופנה 2 סניפים].\n\n1. 3 אתגרים עיקריים של הענף בישראל\n2. כאבים תפעוליים שלא מודעים אליהם\n3. מה גורם לחפש מערכת חדשה?\n4. שאלות שצפוי לשאול\n5. מילים/מושגים שחשוב שאשתמש\n\nקצר – קורא לפני השיחה.", "🆕 שאלה 5: 'שחיקת מלאי' לבעל מיני, 'סוף עונה' לאופנה"), n: "\"שלב 1 – מחקר. דקה אחת. שימו לב לשאלה 5 – שפה ענפית.\n\nלמה זה חשוב? כי כשאני יושב מול בעל מיני ואומר 'שחיקת מלאי' במקום 'אתה מפסיד כסף על סחורה שנזרקת' – הוא מרגיש שאני מבין את העולם שלו.\n\nואם אני מדבר עם בעלת חנות בגדים ואומר 'סוף עונה' ו'מיקס מידות' – היא מרגישה שאני לא סתם סוכן טכנולוגיה.\n\n[הריצו את הפרומפט בזמן אמת, הציגו]\n\n'ראיתם? דקה אחת – כל התמונה. כמו להגיע לדייט ולדעת מה אוהבת לפני שסיפרה.'\"" },
  { c: codeSlide("📋 שלב 2: כרטיס לקוח (באותה שיחה!)", "באותה שיחה! בנה כרטיס:\n\n🏪 [סופר דני 3 סניפים / בוטיק שרון 2 סניפים]\n🖥️ [קופה ישנה / אקסלים / מתחרה]\n👤 [הבעלים / מנהל רכש]\n\n🎯 הזדמנות מרכזית\n⚡ 3 כאבים ספציפיים לענף\n💎 2 פיצ'רים ב-Comax שיפתרו בעיה\n❓ 3 שאלות פתיחה (פגישה או טלפון)\n🛡️ 2 התנגדויות + תשובות\n⚠️ דבר אחד שלא כדאי להגיד", "🔑 AI זוכר את המחקר! הכל מחובר."), n: "\"שלב 2. וכאן הטריק: לא פותחים שיחה חדשה! ממשיכים באותה שיחה. ה-AI כבר יודע מה למד על הענף ועכשיו מקבל את הפרטים הספציפיים.\n\nזה כמו לספר לקולגה: 'אה, ואגב, הלקוח הספציפי הזה – הנה מה שאני יודע.'\n\n[הקלידו, הריצו, הציגו]\n\n'שימו לב למשהו חשוב: ביקשתי \"דבר אחד שלא כדאי להגיד\". זה הזהב. AI לא רק אומר מה לעשות – הוא מזהיר ממוקשים.\n\nלמשל, אם הלקוח פנה אחרי שהמערכת שלו קרסה ביום שישי – לא כדאי להגיד \"כמה כסף הפסדת בגלל המערכת הישנה?\" כי הוא ירגיש שאני מנצל את הכאב. עדיף: \"אני מבין שעברתם יום קשה, בואי נראה שזה לא יקרה שוב.\"\n\nראיתם? AI חושב על דברים שלפעמים גם סוכן מנוסה שוכח.'\"" },
  { c: codeSlide("🗺️ שלב 3: תוכנית (באותה שיחה!)", "המשך שיחה. מטרה: [דמו / קביעת פגישה / הצעה]\n\nלפגישה 30 דק׳:\n⏱️ פתיחה (5) – משפט ראשון, מה לא להגיד\n⏱️ גילוי (10) – 5 שאלות שחושפות צורך\n⏱️ ערך (10) – 3 נקודות + סיפור לקוח דומה\n⏱️ סגירה (5) – משפט מדויק לצעד הבא\n\nלשיחת טלפון 10 דק׳:\n⏱️ פתיחה (1) – hook\n⏱️ גילוי (4) – 3 שאלות ממוקדות\n⏱️ ערך (3) – נקודה חזקה אחת\n⏱️ סגירה (2) – קביעת פגישה/דמו\n\nלכל שלב: מה להגיד, מה לא, סימן אזהרה.", ""), n: "\"ושלב 3 – הכתר. תוכנית פגישה. שימו לב: יש שני מסלולים!\n\nפגישה 30 דקות – 4 שלבים ברורים. פתיחה, גילוי, הצגת ערך, סגירה.\n\nשיחת טלפון 10 דקות – 4 שלבים מקוצרים. בטלפון אין לכם 30 דקות. יש לכם דקה להיפגש ושלוש דקות לגילוי.\n\nשימו לב: ביקשתי 'מה לא להגיד' ו'סימן אזהרה' – מה לעשות כשהפגישה יוצאת מהמסלול.\n\nגם ביקשתי 'משפט מדויק לצעד הבא' – לא סתם 'נדבר', אלא 'מה דעתך שנריץ דמו בסניף אחד ביום ראשון? 30 דקות, בלי התחייבות'.\n\n[הריצו, הציגו]\n\n'ראיתם? 3 פרומפטים. באותה שיחה. 5 דקות. הכנה שלמה שלוקחת שעה לעשות ידנית – או בואו נהיה כנים, שרוב הזמן לא עושים בכלל.'\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 22, bold: true, color: GOLD }, "💪 תרגיל: 5 דקות מול השעון!"), React.createElement(Txt, { size: 14, color: "#ccc" }, "פגישה/שיחה אמיתית. כל 3 השלבים. באותה שיחה."), React.createElement("div", { style: { background: "rgba(244,67,54,0.08)", borderRadius: 14, padding: 16, border: "1px solid rgba(244,67,54,0.3)", textAlign: "center", margin: "12px 0" } }, React.createElement("div", { style: { fontSize: 40, fontWeight: 800, color: "#F44336" } }, "⏱️ 5:00"), React.createElement("div", { style: { fontSize: 13, color: "#F44336" } }, "מחקר → כרטיס → תוכנית")), React.createElement("div", { style: { display: "flex", gap: 8 } }, [{ t: "מחקר", c: "#4FC3F7" }, { t: "כרטיס", c: GOLD }, { t: "תוכנית", c: "#4CAF50" }].map(function(s, i) { return React.createElement("div", { key: i, style: { flex: 1, background: "rgba(255,255,255,0.03)", borderRadius: 10, padding: 10, border: "1px solid " + s.c + "33", textAlign: "center" } }, React.createElement(Txt, { size: 14, bold: true, center: true, color: s.c }, s.t)); })), React.createElement(Txt, { size: 12, color: "#888", center: true }, "אחרי: בזוגות שתפו כרטיסים → 2 מציגים")), n: "\"לא תיאורטי – אמיתי! [טיימר]\n\n'מי סיים? מי הגיע לשלב 3?'\n\n[2 מציגים] 'ראיתם? 5 דקות = הכנה שלמה.'\"" },
  { c: twoColSlide("📊 לפני ואחרי", "😰 בלי AI:", ["הכנה? איזו הכנה?", "נכנס 'ברגשת בטן'", "שוכח לבדוק ענף", "לא מכיר התנגדויות מראש", "פולו-אפ אחרי 3 ימים (אם בכלל)"], "#F44336", "🚀 עם AI:", ["5 דקות = הכנה מלאה", "נכנס עם כרטיס + תוכנית", "מדבר בשפה של הענף", "מוכן להתנגדויות", "פולו-אפ באותו יום"], "#4CAF50"), n: "\"אותו סוכן. אותו כישרון. 5 דקות הכנה = נכנס כאילו הכין יומיים.\"" },
  { c: summarySlide([["📱", "אפליקציה מותקנת", "ChatGPT או Claude"], ["🧠", "5 כללי זהב", "תפקיד → הקשר → משימה → פורמט → שפר"], ["⛓️", "שיטת השרשרת", "מחקר → כרטיס → תוכנית. 5 דקות."], ["📋", "3 תבניות מוכנות", "נשלחות בוואטסאפ"]], "לפני כל פגישה ושיחה – 5 דקות עם AI.\nשלחו ל-\"AI Wins\" כרטיס לקוח + מה קרה."), n: "\"סיכום! היום עשינו המון:\n\n1. הבנו מה AI יכול ומה לא – ומה ההבדל מאוטומציה\n2. הכרנו את הכלים – ChatGPT, Claude, ועוד\n3. כתבנו פרומפטים על לקוחות אמיתיים\n4. למדנו 5 כללי זהב\n5. בנינו שרשרת הכנה מלאה ב-5 דקות\n\nמה אתם לוקחים:\n• אפליקציה מותקנת – מי שעדיין לא, עכשיו!\n• 5 כללי זהב – תפקיד, הקשר, משימה, פורמט, שפר\n• שיטת השרשרת – מחקר, כרטיס, תוכנית\n• 3 תבניות – שולח עכשיו לקבוצת WhatsApp\n\nמשימה: לפני כל פגישה ושיחה – 5 דקות עם AI. שלחו ל-AI Wins כרטיס לקוח לפני, ומה קרה אחרי.\n\nבפעם הבאה – התנגדויות! AI ישחק לקוח קשה ואתם מנסים למכור. מי שמפחד – יתרגל בבית. 🥊\"" },
  { c: closingSlide("מפגש 2: \"התגבר על כל התנגדות\"", "🥊", "AI ישחק לקוח קשה. מי שמפחד – יתרגל בבית 😉"), n: "\"בפעם הבאה Roleplay! שבוע טוב!\"" }
];

/* ========== SESSION 2: התנגדויות ========== */
var S2 = [
  { c: titleSlide(2, 3, '"התגבר על כל התנגדות"', "🛡️ 10 התנגדויות • 3 אסטרטגיות • Roleplay מתקדם • AI כמאמן אישי"), n: "\"היום הכי כיפי! AI הופך ללקוח קשה – בעל מיני שאומר 'יקר', בעלת בוטיק שאומרת 'לא עכשיו'. ואתם מנסים למכור.\n\nלפני שנריב עם AI – נבנה ביחד את מאגר הנשק.\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 24, bold: true, color: GOLD }, "🏆 מה קרה מאז?"), React.createElement(Txt, { size: 14, color: "#ccc" }, "מי הכין פגישה/שיחה עם שיטת השרשרת? מה קרה?"), React.createElement("div", { style: { display: "flex", gap: 14, marginTop: 14 } }, React.createElement("div", { style: { flex: 1, background: "rgba(76,175,80,0.08)", borderRadius: 12, padding: 14, border: "1px solid rgba(76,175,80,0.2)" } }, React.createElement(Txt, { size: 15, bold: true, color: "#4CAF50" }, "✅ הצלחות"), React.createElement(Txt, { size: 13, color: "#aaa" }, "\"הלקוח שאל איך אני יודע כל כך הרבה\"")), React.createElement("div", { style: { flex: 1, background: "rgba(244,67,54,0.08)", borderRadius: 12, padding: 14, border: "1px solid rgba(244,67,54,0.2)" } }, React.createElement(Txt, { size: 15, bold: true, color: "#F44336" }, "🤔 אתגרים"), React.createElement(Txt, { size: 13, color: "#aaa" }, "\"הכנתי הכנה ואז אמר 'יקר' ונתקעתי\""))), React.createElement(GoldBox, null, React.createElement(Txt, { size: 15, color: GOLD, bold: true, center: true }, "🎯 הכנה + תשובות להתנגדויות = בלתי ניתן לעצירה!"))), n: "\"סיבוב: מי הכין? מה קרה?\n\n'הכנה = חצי. החצי השני = לדעת מה לענות כשאומר לא.'\"" },
  { c: twoColSlide("🗣️ 10 ההתנגדויות הנפוצות", "💰 כסף ותזמון:", ["1. \"יקר לי\"", "2. \"לא עכשיו, אולי בשנה הבאה\"", "3. \"רוצה לראות עוד הצעות\"", "4. \"אין לי זמן לזה\"", "5. \"מה אם זה לא עובד?\""], "#F44336", "🖥️ מערכת ושינוי:", ["6. \"יש לי כבר מערכת/קופה\"", "7. \"צריך לדבר עם השותף/רו\"ח\"", "8. \"המעבר מסובך מדי\"", "9. \"למה Comax ולא המתחרה?\"", "10. \"העובדים/הצוות לא יסכימו\""], GOLD), n: "\"10 קלאסיקות. כסף/תזמון ומערכת/שינוי.\n\nמה חסר? [רשמו]. עכשיו – 3 תשובות לכל אחת.\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 22, bold: true, color: GOLD }, "🧠 3 אסטרטגיות לכל התנגדות"), React.createElement("div", { style: { display: "flex", gap: 10, flex: 1, marginTop: 10 } }, [{ t: "🔄 הפוך", d: "שאלה שמשנה\nפרספקטיבה", ex: "\"כמה עולה לך\nלא לדעת את המלאי?\"", c: "#4FC3F7" }, { t: "💎 ערך", d: "הראה ROI\nעם מספרים", ex: "\"לקוח דומה חסך\n40 שעות/חודש\"", c: GOLD }, { t: "🤝 רכך", d: "הסכם +\nצעד קטן", ex: "\"מבין. בוא נתחיל\nמדמו חינם בסניף אחד\"", c: "#4CAF50" }].map(function(x, i) { return React.createElement("div", { key: i, style: { flex: 1, background: x.c + "11", borderRadius: 14, padding: 12, border: "1px solid " + x.c + "44", display: "flex", flexDirection: "column" } }, React.createElement(Txt, { size: 15, bold: true, color: x.c, center: true }, x.t), React.createElement(Txt, { size: 11, color: "#aaa", center: true }, x.d), React.createElement("div", { style: { background: "rgba(0,0,0,0.2)", borderRadius: 8, padding: 8, marginTop: "auto" } }, React.createElement(Txt, { size: 11, color: "#ddd" }, x.ex))); }))), n: "\"3 דרכים: הפוך (שאלה), ערך (מספרים), רכך (צעד קטן).\n\nלמה 3? כי כל לקוח שונה. רציונלי = מספרים. רגשי = הבנה. זהיר = צעד קטן.\"" },
  { c: codeSlide("🖥️ AI בונה תשובות – הדגמה", "אתה מומחה מכירות 20 שנות ניסיון + פסיכולוגיית מכירות.\nמכיר קמעונאות מזון ואופנה בישראל.\n\nלקוח (בעל מיני / חנות בגדים) אומר: \"יקר לי\"\n\n3 אסטרטגיות:\n🔄 הפוך: שאלה שמשנה פרספקטיבה\n💎 ערך: ROI עם דוגמה מספרית מהענף\n🤝 רכך: הסכמה חלקית + צעד קטן\n\nלכל אחת:\n• משפט מילה במילה (טבעי, לא תסריט!)\n• למה עובד פסיכולוגית (משפט אחד)\n• מתי להשתמש – פגישה פיזית או טלפון\n• מה להגיד אחרי שהלקוח מגיב", ""), n: "\"[הרץ בזמן אמת] שימו לב: תפקיד כפול – מכירות ופסיכולוגיה.\n\n'מתי – פגישה או טלפון'. בטלפון = קצר יותר.\n'מה ההמשך' – כי לקוח לא שומע תשובה ונכנע.\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 22, bold: true, color: GOLD }, "💪 תרגיל קבוצתי: בונים את המאגר"), React.createElement(Txt, { size: 13, color: "#aaa" }, "3 קבוצות. כל קבוצה 3 התנגדויות + AI. מציגים הטובה ביותר."), React.createElement("div", { style: { display: "flex", gap: 10, flex: 1, marginTop: 10 } }, [{ n: "קבוצה א׳", items: ["\"יקר לי\"", "\"לא עכשיו\"", "\"עוד הצעות\""], c: "#4FC3F7" }, { n: "קבוצה ב׳", items: ["\"יש מערכת\"", "\"צריך השותף\"", "\"אין זמן\""], c: GOLD }, { n: "קבוצה ג׳", items: ["\"המעבר מסובך\"", "\"למה Comax?\"", "\"הצוות לא יסכים\""], c: "#4CAF50" }].map(function(g, i) { return React.createElement("div", { key: i, style: { flex: 1, background: "rgba(255,255,255,0.03)", borderRadius: 12, padding: 12, border: "1px solid " + g.c + "33" } }, React.createElement(Txt, { size: 14, bold: true, color: g.c, center: true }, g.n), React.createElement("div", { style: { marginTop: 6 } }, g.items.map(function(item, j) { return React.createElement("div", { key: j, style: { background: "rgba(0,0,0,0.2)", borderRadius: 6, padding: "4px 8px", marginBottom: 4 } }, React.createElement(Txt, { size: 12, color: "#ddd" }, item)); }))); })), React.createElement("div", { style: { display: "flex", gap: 8, marginTop: 8 } }, React.createElement("div", { style: { flex: 1, background: "rgba(232,185,49,0.08)", borderRadius: 8, padding: 8, textAlign: "center" } }, React.createElement(Txt, { size: 13, color: GOLD, bold: true, center: true }, "15 דק׳ עבודה")), React.createElement("div", { style: { flex: 1, background: "rgba(232,185,49,0.08)", borderRadius: 8, padding: 8, textAlign: "center" } }, React.createElement(Txt, { size: 13, color: GOLD, bold: true, center: true }, "10 דק׳ הצגה")))), n: "\"3 קבוצות × 3 התנגדויות × 3 אסטרטגיות = 27 תשובות!\n\n'אל תקחו תשובה ראשונה! בקשו: יותר ישיר, יותר טבעי, גישה הפוכה.'\"" },
  { c: React.createElement(CenterSlide, null, React.createElement("div", { style: { fontSize: 56 } }, "🥊"), React.createElement(Txt, { size: 32, bold: true, color: GOLD, center: true }, "Roleplay"), React.createElement(Txt, { size: 18, color: "#ccc", center: true }, "AI ישחק לקוח. אתם מוכרים."), React.createElement(Txt, { size: 14, color: "#888", center: true }, "(AI לא ייתן לנצח בקלות 😈)")), n: "\"AI הולך להיות נגדכם. קשה, ריאלי.\n\nאבל גם ייתן ציון וטיפים. גם אם 'תפסידו' – תצאו חכמים יותר.\"" },
  { c: codeSlide("🎭 פרומפט Roleplay מתקדם", "אתה לקוח בסימולציית מכירה.\n\nפרופיל – בחר:\n• דני, רשת מיני 4 סניפים, חסכן, ממהר\n• שרון, בוטיק אופנה 2 סניפים, עסוקה מאוד\n• מוחמד, סופר שכונתי, חתום עם מתחרה\n• רונית, רשת ביגוד ספורט, מפחדת מטכנולוגיה\n\nכללים:\n• התנגד לפחות 4 פעמים לפני פתיחות\n• התנגדויות מגוונות – לא רק 'יקר'\n• באמצע: \"שמע, המתחרה הציע זול יותר אתמול\"\n• בטלפון: 'אני באמצע משהו, יש לך דקה'\n• בסוף: ציון 1-10, 3 טוב, 3 לשפר, המשפט שהכי שכנע", ""), n: "\"4 פרופילים. מזון ואופנה. גם אופציית טלפון.\n\n[הדגם על המסך עם מתנדב]\n\n[אחר כך כולם – 10 דק׳ Roleplay, ציון, החלפה]\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 20, bold: true, color: GOLD }, "🎴 פרופילי לקוחות"), React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, flex: 1, marginTop: 10 } }, [{ n: "דני", b: "רשת מיני, 4 סניפים", f: "\"יש לך 3 דקות\"", c: "#4FC3F7", d: "⭐⭐" }, { n: "שרון", b: "בוטיק אופנה, 2 סניפים", f: "\"שלחו מייל, אין זמן\"", c: GOLD, d: "⭐⭐⭐" }, { n: "מוחמד", b: "סופר שכונתי", f: "\"חתום עם המתחרה\"", c: "#4CAF50", d: "⭐⭐⭐" }, { n: "רונית", b: "רשת ביגוד ספורט", f: "\"אני לא מבינה במחשבים\"", c: "#F44336", d: "⭐⭐⭐⭐" }].map(function(p, i) { return React.createElement("div", { key: i, style: { background: "rgba(255,255,255,0.03)", borderRadius: 12, padding: 12, border: "1px solid " + p.c + "33" } }, React.createElement("div", { style: { display: "flex", justifyContent: "space-between", marginBottom: 4 } }, React.createElement(Txt, { size: 11, color: p.c }, p.d), React.createElement(Txt, { size: 15, bold: true, color: p.c }, p.n)), React.createElement(Txt, { size: 12, color: "#ccc" }, "📍 " + p.b), React.createElement("div", { style: { background: "rgba(0,0,0,0.3)", borderRadius: 6, padding: "4px 8px", marginTop: 4 } }, React.createElement(Txt, { size: 12 }, p.f))); })), React.createElement(Txt, { size: 12, color: GOLD, center: true }, "10 דק׳ Roleplay → ציון → החלפת פרופיל")), n: "\"דני – ממהר. שרון – מעדיפה מייל. מוחמד – חתום. רונית – מפחדת.\n\n[כל אחד בוחר, 10 דק׳, ציון, החלפה]\"" },
  { c: breakSlide("אם AI נתן ציון נמוך – הוא מחמיא יותר מהמנהל שלכם"), n: "\"הפסקה!\"" },
  { c: codeSlide("🧪 Pro: ניתוח פגישה/שיחה בדיעבד", "אתה מאמן מכירות. חוזר מ[פגישה / שיחת טלפון].\n\n• הלקוח: [מיני/אופנה, מצב]\n• הוא אמר: [התנגדויות – ציטוט]\n• אני עניתי: [מה אמרתי – ציטוט]\n• תוצאה: [סגירה? דחייה? 'נדבר'? ניתוק?]\n\nתן:\n1. ניתוח: מה נכון, מה הייתי עושה אחרת\n2. 3 תשובות טובות יותר להתנגדויות שהיו\n3. אם 'נדבר'/ניתוק – מה הפולו-אפ הנכון\n4. שיעור אחד שלוקח לפגישה/שיחה הבאה\n\nתהיה ישיר. אל תחמיא – אני רוצה ללמוד.", "💡 כל פגישה/שיחה = שיעור. גם כשלא סוגרים."), n: "\"הכלי הכי חזק! אחרי כל פגישה/שיחה – ברכב, הזינו.\n\n'אל תחמיא'. כל פגישה – גם כושלת – הופכת לשיעור.\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 20, bold: true, color: GOLD }, "🛡️ תרגיל: המאגר האישי שלכם"), React.createElement("div", { style: { background: "#1a1a2e", borderRadius: 12, padding: 12, border: "1px solid #333", fontFamily: "monospace", marginTop: 8, flex: 1, overflow: "auto" } }, React.createElement(Txt, { size: 11, color: "#ddd" }, "אני סוכן Comax. עובד עם [מזון / אופנה].\n\nה-5 התנגדויות שאני שומע הכי הרבה:\n1. [___]\n2. [___]\n3. [___]\n4. [___]\n5. [___]\n\nלכל אחת:\n• תשובה מיידית (2-3 משפטים, טבעי!)\n• שאלה שמפנה את השיחה\n• משפט דחיפות עדין\n\nמותאם ל[פגישה / טלפון].")), React.createElement("div", { style: { display: "flex", gap: 8, marginTop: 8 } }, [{ t: "10 דק׳", d: "בנו מאגר" }, { t: "10 דק׳", d: "בזוגות: 'התנגדות → תשובה'" }, { t: "5 דק׳", d: "שיתוף" }].map(function(s, i) { return React.createElement("div", { key: i, style: { flex: 1, background: "rgba(232,185,49,0.06)", borderRadius: 8, padding: 8, textAlign: "center" } }, React.createElement(Txt, { size: 13, color: GOLD, bold: true, center: true }, s.t), React.createElement(Txt, { size: 11, color: "#aaa", center: true }, s.d)); }))), n: "\"כל אחד בונה מאגר אישי. 5 התנגדויות שלכם.\n\n[10 דק׳ בנייה] [10 דק׳ זוגות: 'תגיד התנגדות – אני עונה'] [5 דק׳ שיתוף]\"" },
  { c: summarySlide([["🛡️", "מאגר 15 תשובות", "5 התנגדויות × 3 אסטרטגיות"], ["🥊", "Roleplay מתקדם", "4 פרופילים, פגישה + טלפון"], ["📊", "ניתוח בדיעבד", "כל שיחה = שיעור"], ["🧠", "3 אסטרטגיות", "הפוך / ערך / רכך"]], "כל התנגדות → AI ברכב.\n2 Roleplay בבית – פגישה אחת, טלפון אחד.\nשתפו ב-AI Wins."), n: "\"מאגר, Roleplay, ניתוח, 3 אסטרטגיות.\n\nמשימה: כל התנגדות → AI. 2 Roleplay בבית.\n\nבפעם הבאה – כתיבה + Mega Prompt + ערכה אישית! ✍️\"" },
  { c: closingSlide("מפגש 3: \"כתיבה, סגירה והסוכן החכם\"", "✍️", "תביאו הצעת מחיר ישנה – נשדרג בזמן אמת! 😎"), n: "\"בפעם הבאה: כתיבה + Mega Prompt. תביאו הצעת מחיר ישנה!\"" }
];

/* ========== SESSION 3: כתיבה + סגירה ========== */
var S3 = [
  { c: titleSlide(3, 3, '"כתיבה, סגירה והסוכן החכם"', "✍️ Multi-shot • Persona Chain • Mega Prompt • ערכה אישית • סיכום"), n: "\"המפגש האחרון! היום: כתיבה שמוכרת + Mega Prompt + ערכה אישית. מגיעים מוכנים לשטח.\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 24, bold: true, color: GOLD }, "🏆 מה קרה מאז?"), React.createElement("div", { style: { display: "flex", gap: 14, marginTop: 14 } }, React.createElement("div", { style: { flex: 1, background: "rgba(232,185,49,0.06)", borderRadius: 12, padding: 14, border: "1px solid rgba(232,185,49,0.2)" } }, React.createElement(Txt, { size: 15, bold: true, color: GOLD }, "📊 ניתוח פגישות"), React.createElement(Txt, { size: 13, color: "#aaa" }, "מי הזין ל-AI? מה למדתם?")), React.createElement("div", { style: { flex: 1, background: "rgba(232,185,49,0.06)", borderRadius: 12, padding: 14, border: "1px solid rgba(232,185,49,0.2)" } }, React.createElement(Txt, { size: 15, bold: true, color: GOLD }, "🥊 Roleplay בבית"), React.createElement(Txt, { size: 13, color: "#aaa" }, "מה הציון? מה למדתם?")))), n: "\"סיבוב: ניתוח פגישות? Roleplay בבית?\n\n'היום טכניקות שרוב אנשי שיווק לא מכירים. ומפגש סיכום.'\"" },
  { c: React.createElement(CenterSlide, null, React.createElement(Txt, { size: 22, bold: true, color: GOLD, center: true }, "הבעיה עם תקשורת כתובה"), React.createElement("div", { style: { display: "flex", gap: 12, marginTop: 12 } }, [{ i: "📱", t: "WhatsApp", b: "\"היי, אני מ-Comax...\"", s: "2/10" }, { i: "📧", t: "פולו-אפ", b: "\"היה נחמד. מחכה.\"", s: "1/10" }, { i: "📄", t: "הצעת מחיר", b: "\"רצ\"ב. בברכה.\"", s: "3/10" }].map(function(x, i) { return React.createElement("div", { key: i, style: { flex: 1, background: "rgba(244,67,54,0.06)", borderRadius: 12, padding: 12, border: "1px solid rgba(244,67,54,0.2)", textAlign: "center" } }, React.createElement("div", { style: { fontSize: 24 } }, x.i), React.createElement(Txt, { size: 13, bold: true, center: true }, x.t), React.createElement(Txt, { size: 11, color: "#F44336", center: true }, x.b), React.createElement("div", { style: { fontSize: 16, fontWeight: 800, color: "#F44336", marginTop: 4 } }, x.s)); })), React.createElement(Txt, { size: 14, color: "#ccc", center: true }, "50 הודעות ביום. למה שיקרא שלכם?")), n: "\"הלקוח מקבל 50 הודעות. 'היי אני מ-Comax' = ספאם.\n\nהיום – כל הודעה תהיה שונה. מקצועית. ובעיקר – כזו שפותחים.\"" },
  { c: codeSlide("🧪 Multi-shot: AI בסגנון שלכם", "למד את הסגנון שלי מ-3 דוגמאות.\n\n3 הודעות WhatsApp שכתבתי ועבדו:\n\nדוגמה 1: \"[הודעה ללקוח מזון שעבדה]\"\nדוגמה 2: \"[הודעה ללקוח אופנה]\"\nדוגמה 3: \"[עוד אחת]\"\n\nבסגנון הזה כתוב הודעה חדשה:\n• לקוח: [בעל סופר / חנות בגדים]\n• מטרה: [קביעת פגישה / פולו-אפ / חימום]\n\nשמור על הטון, האורך, הסגנון שלי.\nאל תהיה יותר פורמלי.", "💡 AI כותב כמוכם – לא כרובוט. Pro level."), n: "\"Multi-shot: 3 דוגמאות שעבדו = AI כותב כמוכם. ההבדל בין חודש שימוש לשבוע.\"" },
  { c: codeSlide("📱 פולו-אפ – 3 הודעות ברצף", "היה לי [פגישה / שיחת טלפון]:\n\nלקוח: [בעל רשת מיני / בעלת בוטיק]\nדיברנו: [מה הצגתי, מה עניין]\nהתנגדות: [מה אמר]\nסיכמנו: [צעד הבא]\n\n3 הודעות WhatsApp:\n1. מיד אחרי – סיכום חם, מזכיר מה הכי עניין\n2. יום לפני – תזכורת + ערך (טיפ לענף שלו)\n3. אם לא עונה – לא רודף. שאלה שקל לענות.\n\nמקס 4 שורות. בלי 'שלום רב', בלי 'בברכה'.", ""), n: "\"לא הודעה – סדרה! הודעה 2: ערך = יועץ. 'ראיתי שמחירי סחורה עולים – חשבתי עליך.'\"" },
  { c: codeSlide("🔗 Persona Chain – AI בודק את AI", "שלב 1: כתוב הצעה / WhatsApp / פולו-אפ\n[AI כותב...]\n\n──────────────────\n\nשלב 2: עכשיו שכח שכתבת.\nאתה הלקוח – [בעל סופר חסכן / בעלת בוטיק עסוקה].\n\nקראת את ההודעה. תן ציון:\n• הייתי פותח? כן/לא ולמה\n• מה הרגשתי כלקוח?\n• מה היה גורם להגיב? למחוק?\n• תשכתב – גרסה שהייתי באמת מגיב\n\nשלב 3: חזור לכותב. תקן לפי הביקורת.", "כותב → מבקר כלקוח → משכתב. דקה וחצי = יהלום."), n: "\"הטכניקה הכי מתקדמת! AI כותב, מבקר, מתקן. 3 שכבות.\n\nהגרסה השלישית = שנתיים אור מהראשונה.\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 20, bold: true, color: GOLD }, "💪 כתבו. שלחו. עכשיו!"), React.createElement(Txt, { size: 14, color: "#ccc" }, "לקוח אמיתי שצריך הודעה. מי שאמיץ – שולח ממש עכשיו!"), React.createElement("div", { style: { display: "flex", gap: 10, margin: "12px 0" } }, [{ t: "7 דק׳", d: "כתבו עם AI" }, { t: "5 דק׳", d: "בזוגות: טבעי?" }, { t: "3 דק׳", d: "מי שולח?! 🚀" }].map(function(s, i) { return React.createElement("div", { key: i, style: { flex: 1, background: "rgba(232,185,49,0.06)", borderRadius: 10, padding: 10, textAlign: "center", border: "1px solid rgba(232,185,49,0.15)" } }, React.createElement("div", { style: { fontSize: 15, fontWeight: 700, color: GOLD } }, s.t), React.createElement(Txt, { size: 12, color: "#aaa", center: true }, s.d)); })), React.createElement("div", { style: { background: "rgba(244,67,54,0.06)", borderRadius: 12, padding: 14, border: "1px solid rgba(244,67,54,0.2)", textAlign: "center" } }, React.createElement("div", { style: { fontSize: 18, color: "#F44336", fontWeight: 700 } }, "⚡ מי שולח הודעה ללקוח אמיתי?"))), n: "\"רגע האמת! [אם מישהו שולח ומקבל תשובה בסדנה – זהב טהור!]\"" },
  { c: breakSlide("בדקו WhatsApp. אולי מישהו כבר ענה 😏"), n: "\"הפסקה! אחרי – Mega Prompt והערכה האישית.\"" },
  { c: codeSlide("🧠 Mega Prompt – הנשק הסודי", "עוזר AI למכירות Comax – ERP וקופות POS\nלקמעונאות מזון ואופנה.\n\nהלקוח: [שם, סוג עסק, גודל, מיקום]\nידוע: [מערכת, מצב, איך הגעתי]\nמטרה: [דמו / הצעה / סגירה / קביעת פגישה]\nסוג: [פגישה פיזית / שיחת טלפון]\n\nחבילת הכנה מלאה:\n1. מחקר ענפי – אתגרים, כאבים, שפה ענפית\n2. כרטיס לקוח – הזדמנות, שאלות, התנגדויות\n3. תוכנית [פגישה 30 דק׳ / שיחה 10 דק׳]\n4. 3 התנגדויות × 3 אסטרטגיות\n5. 3 הודעות פולו-אפ WhatsApp\n6. דבר אחד לא להגיד + אזהרות\n\nקורא ב-5 דק׳ לפני.", "פרומפט אחד = חבילה שלמה. דקה וחצי."), n: "\"Mega Prompt. הכל בבת אחת. דקה וחצי – חבילה שלמה.\n\nזה הכלי שתשתמשו 90% מהזמן. ממלאים סוגריים, שולחים, קוראים בדרך.\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 22, bold: true, color: GOLD }, "🏆 תחרות הפרומפטים!"), React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, flex: 1, marginTop: 12 } }, [{ c: "🎨 הכי יצירתי", cl: "#9C27B0" }, { c: "💰 הכי מכירתי", cl: GOLD }, { c: "⏱️ חוסך זמן", cl: "#4FC3F7" }, { c: "🤯 הכי מפתיע", cl: "#F44336" }].map(function(x, i) { return React.createElement("div", { key: i, style: { background: "rgba(255,255,255,0.03)", borderRadius: 12, padding: 14, border: "1px solid " + x.cl + "44", textAlign: "center" } }, React.createElement("div", { style: { fontSize: 15, fontWeight: 700, color: x.cl } }, x.c)); })), React.createElement(GoldBox, null, React.createElement(Txt, { size: 12, color: "#ccc" }, "10 דק׳ בנייה • 60 שניות הצגה • הצבעה • המנצחים → ספר הפרומפטים של Comax"))), n: "\"4 קטגוריות. 10 דקות. 60 שניות כל אחד. המנצחים → ספר הפרומפטים!\"" },
  { c: React.createElement(Slide, null, React.createElement(Txt, { size: 20, bold: true, color: GOLD }, "🧰 ערכה אישית – 5 פרומפטים"), React.createElement("div", { style: { display: "flex", flexDirection: "column", gap: 6, flex: 1, marginTop: 10 } }, [{ n: "☀️", t: "פרומפט בוקר", d: "פגישות/שיחות היום, טיפ לכל אחת", c: "#F7D060" }, { n: "🎯", t: "Mega Prompt", d: "חבילת הכנה מלאה", c: GOLD }, { n: "🆘", t: "חירום", d: "בדרך ללקוח, 2-3 נקודות", c: "#F44336" }, { n: "📊", t: "ניתוח פגישה", d: "מה טוב, מה אשפר, פולו-אפ", c: "#4FC3F7" }, { n: "🌙", t: "סיכום יום", d: "מה היה, דחוף למחר", c: "#9C27B0" }].map(function(x, i) { return React.createElement("div", { key: i, style: { display: "flex", gap: 10, alignItems: "center", background: "rgba(255,255,255,0.03)", borderRadius: 8, padding: "8px 12px", border: "1px solid #2a2a4a" } }, React.createElement("div", { style: { fontSize: 20 } }, x.n), React.createElement("div", { style: { flex: 1 } }, React.createElement(Txt, { size: 13, bold: true, color: x.c }, x.t), React.createElement(Txt, { size: 11, color: "#aaa" }, x.d))); })), React.createElement("div", { style: { display: "flex", gap: 8, marginTop: 6 } }, React.createElement("div", { style: { flex: 1, background: "rgba(232,185,49,0.06)", borderRadius: 8, padding: 6, textAlign: "center" } }, React.createElement(Txt, { size: 12, color: GOLD, bold: true, center: true }, "15 דק׳ בנו")), React.createElement("div", { style: { flex: 1, background: "rgba(232,185,49,0.06)", borderRadius: 8, padding: 6, textAlign: "center" } }, React.createElement(Txt, { size: 12, color: GOLD, bold: true, center: true }, "10 דק׳ שתפו")))), n: "\"הדבר הכי חשוב! 5 פרומפטים מותאמים אישית.\n\n15 דקות. מה שיצא = מה שתשתמשו בשנה הקרובה.\"" },
  { c: twoColSlide("איפה AI ואיפה אני?", "🤖 AI:", ["מחקר ענפי", "ניסוח הודעות", "רעיונות", "תרגול", "ניתוח", "24/7"], "#4FC3F7", "🧑 אתם:", ["קשר אישי", "טון בטלפון", "אינטואיציה", "גמישות", "סגירה", "קפה ☕"], GOLD), n: "\"AI מכין. אתם סוגרים. ביחד – בלתי ניתנים לעצירה.\"" },
  { c: summarySlide([["✍️", "Multi-shot + Persona Chain", "AI כותב בסגנון שלכם"], ["🧠", "Mega Prompt", "הכל בפרומפט אחד"], ["🧰", "ערכה אישית", "5 פרומפטים מותאמים"], ["🏆", "ספר הפרומפטים", "הפרומפטים המנצחים"]], "אתגר 30 יום: AI כל יום – לפני כל פגישה ושיחה.\nשתפו ב-AI Wins. בעוד חודש ניפגש לבדוק."), n: "\"30 יום – AI כל יום.\n\nבעוד חודש ניפגש לשעה – מה השתנה.\"" },
  { c: React.createElement(CenterSlide, { gap: 16 }, React.createElement(Badge), React.createElement(Txt, { size: 24, bold: true, center: true }, "🎓 סיום הסדנה!"), React.createElement(Divider), React.createElement("div", { style: { fontSize: 40 } }, "🚀"), React.createElement(GoldBox, null, React.createElement(Txt, { size: 15, center: true }, "התחלנו: \"מה AI יכול בשבילי?\""), React.createElement(Txt, { size: 15, color: GOLD, bold: true, center: true }, "עכשיו: \"מה אני יכול עם AI?\""), React.createElement(Txt, { size: 15, center: true }, "תשובתי: כמעט הכל.")), React.createElement(Txt, { size: 13, color: "#888", center: true }, "אתגר 30 יום • AI Wins • נתראה בעוד חודש!")), n: "\"'מה AI עושה בשבילי? → מה אני עושה עם AI? כמעט הכל.'\n\nתודה! אתם אלופים! 🚀\"" }
];

var SESSIONS = [
  { id: 1, title: "מהתחלה לפגישה", emoji: "💡", sub: "שבירת חסמים + שרשרת הכנה", slides: S1 },
  { id: 2, title: "התגבר על כל התנגדות", emoji: "🛡️", sub: "מאגר + Roleplay + ניתוח", slides: S2 },
  { id: 3, title: "כתיבה, סגירה והסוכן החכם", emoji: "✍️", sub: "Multi-shot + Mega Prompt + ערכה", slides: S3 }
];

/* ===== EXPORT ===== */
function exportHTML(sid) { var s = SESSIONS.find(function(x) { return x.id === sid; }); var h = '<!DOCTYPE html><html dir="rtl"><head><meta charset="UTF-8"><title>Comax - מפגש ' + s.id + '</title><style>body{background:#0f0f1a;font-family:sans-serif;direction:rtl;padding:20px}.s{max-width:800px;margin:20px auto;background:#1a1a2e;border-radius:16px;padding:30px;border:1px solid #2a2a4a;min-height:300px;page-break-after:always}.g{color:#E8B931}.n{text-align:center;color:#888;font-size:12px;margin:8px 0}</style></head><body><div style="text-align:center;color:#E8B931;font-size:22px;font-weight:800;padding:20px">COMAX × AI | מפגש ' + s.id + '</div>'; s.slides.forEach(function(sl, i) { h += '<div class="s"><div style="color:#E8B931;font-size:16px;font-weight:700;text-align:right">שקף ' + (i + 1) + '</div></div><div class="n">' + (i + 1) + '/' + s.slides.length + '</div>'; }); h += '</body></html>'; var b = new Blob([h], { type: "text/html;charset=utf-8" }); var u = URL.createObjectURL(b); var a = document.createElement("a"); a.href = u; a.download = "comax-session-" + sid + ".html"; document.body.appendChild(a); a.click(); document.body.removeChild(a); }
function printSession(sid) { var s = SESSIONS.find(function(x) { return x.id === sid; }); var w = window.open("", "_blank"); var h = '<!DOCTYPE html><html dir="rtl"><head><meta charset="UTF-8"><title>Comax - מפגש ' + s.id + '</title><style>body{font-family:sans-serif;direction:rtl;padding:20px}.p{border:2px solid #E8B931;border-radius:12px;padding:20px;margin:0 0 20px;page-break-after:always}h2{color:#E8B931;font-size:16px}.nt{background:#f9f5e8;border-right:4px solid #E8B931;padding:12px;border-radius:6px;font-size:13px;line-height:1.8}</style></head><body><div style="text-align:center;font-size:20px;font-weight:800;color:#E8B931;border-bottom:2px solid #E8B931;padding-bottom:10px;margin-bottom:20px">COMAX × AI | מפגש ' + s.id + ': "' + s.title + '"</div>'; s.slides.forEach(function(sl, i) { var nt = (sl.n || "").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br>"); h += '<div class="p"><h2>שקף ' + (i + 1) + '/' + s.slides.length + '</h2><div class="nt"><b>🎤 הערות:</b><br>' + nt + '</div></div>'; }); h += '<script>setTimeout(function(){window.print()},500)<\/script></body></html>'; w.document.write(h); w.document.close(); }

/* ===== SCREENS ===== */
function WaitingScreen() {
  var _d = useState(0), dots = _d[0], setDots = _d[1]; var _t = useState(0), tip = _t[0], setTip = _t[1]; var _tm = useState(""), time = _tm[0], setTime = _tm[1];
  useEffect(function() { var i = setInterval(function() { setDots(function(d) { return (d + 1) % 4; }); }, 800); return function() { clearInterval(i); }; }, []);
  useEffect(function() { var i = setInterval(function() { setTip(function(t) { return t + 1; }); }, 6000); return function() { clearInterval(i); }; }, []);
  useEffect(function() { var u = function() { setTime(new Date().toLocaleTimeString("he-IL", { hour: "2-digit", minute: "2-digit", second: "2-digit" })); }; u(); var i = setInterval(u, 1000); return function() { clearInterval(i); }; }, []);
  var tips = ["💡 AI יכול להכין פגישה ב-5 דקות", "🤖 AI לא ישן ולא מתלונן על בונוס", "📱 וודאו ש-ChatGPT או Claude מותקנים", "☕ בינתיים קפה. ל-AI לא צריך.", "🧠 סוכן + AI = בלתי ניתן לעצירה", "📞 עובד גם לפני שיחת טלפון!"];
  return React.createElement("div", { style: { width: "100%", minHeight: "100vh", background: DARK, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Segoe UI',sans-serif", direction: "rtl" } }, React.createElement("div", { style: { textAlign: "center", maxWidth: 420, padding: 24 } }, React.createElement("div", { style: { marginBottom: 48 } }, React.createElement("div", { style: { width: 90, height: 90, borderRadius: 45, background: "linear-gradient(135deg," + GOLD + ",#F7D060)", margin: "0 auto 20px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 38, fontWeight: 800, color: "#1a1a2e" } }, "C"), React.createElement("div", { style: { fontSize: 26, fontWeight: 800, color: GOLD, letterSpacing: 2 } }, "COMAX × AI"), React.createElement("div", { style: { fontSize: 16, color: "#888", marginTop: 6 } }, "סדנת AI למכירות שטח")), React.createElement("div", { style: { fontSize: 52, fontWeight: 300, color: "#fff", marginBottom: 40, fontVariantNumeric: "tabular-nums", fontFamily: "monospace" } }, time), React.createElement("div", { style: { marginBottom: 48 } }, React.createElement("div", { style: { display: "flex", justifyContent: "center", gap: 10, marginBottom: 20 } }, [0, 1, 2].map(function(i) { return React.createElement("div", { key: i, style: { width: 12, height: 12, borderRadius: 6, background: GOLD, opacity: (dots + i) % 4 === 0 ? 1 : 0.25, transition: "opacity 0.4s" } }); })), React.createElement("div", { style: { fontSize: 20, color: "#aaa" } }, "קצת סבלנות, עוד מעט מתחילים" + ".".repeat(dots))), React.createElement("div", { style: { background: "rgba(232,185,49,0.06)", border: "1px solid rgba(232,185,49,0.15)", borderRadius: 16, padding: "16px 24px" } }, React.createElement("div", { style: { fontSize: 15, color: "#888" } }, tips[tip % tips.length]))));
}

function LoginScreen(p) {
  var _pw = useState(""), pw = _pw[0], setPw = _pw[1]; var _e = useState(false), err = _e[0], setErr = _e[1];
  function go() { if (pw === PASSWORD) p.onLogin(); else setErr(true); }
  return React.createElement("div", { style: { width: "100%", minHeight: "100vh", background: DARK, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Segoe UI',sans-serif", direction: "rtl" } }, React.createElement("div", { style: { maxWidth: 420, width: "100%", padding: 24, textAlign: "center" } }, React.createElement("div", { style: { width: 80, height: 80, borderRadius: 40, background: "linear-gradient(135deg," + GOLD + ",#F7D060)", margin: "0 auto 20px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 34, fontWeight: 800, color: "#1a1a2e" } }, "C"), React.createElement("div", { style: { fontSize: 24, fontWeight: 800, color: GOLD, letterSpacing: 2, marginBottom: 4 } }, "COMAX × AI"), React.createElement("div", { style: { fontSize: 16, color: "#888", marginBottom: 32 } }, "כניסת מנחה"), React.createElement("div", { style: { display: "flex", gap: 10, justifyContent: "center", direction: "ltr", marginBottom: 12 } }, React.createElement("input", { type: "password", placeholder: "סיסמה", value: pw, onChange: function(e) { setPw(e.target.value); setErr(false); }, onKeyDown: function(e) { if (e.key === "Enter") go(); }, style: { background: "rgba(255,255,255,0.06)", border: "1px solid " + (err ? "#F44336" : "#444"), borderRadius: 12, padding: "12px 18px", color: "#fff", fontSize: 16, textAlign: "center", width: 180, outline: "none" } }), React.createElement("button", { onClick: go, style: { background: GOLD, color: "#1a1a2e", border: "none", borderRadius: 12, padding: "12px 24px", fontWeight: 700, fontSize: 16, cursor: "pointer" } }, "כניסה")), err ? React.createElement("div", { style: { color: "#F44336", fontSize: 14 } }, "סיסמה שגויה") : null));
}

function Dashboard(p) {
  var base = typeof window !== "undefined" ? window.location.origin + window.location.pathname : "";
  var _c = useState(false), copied = _c[0], setCopied = _c[1]; var _cs = useState(0), cs = _cs[0], setCs = _cs[1];
  function copyLink(sid) { var u = base + "?view=true&session=" + sid; var ta = document.createElement("textarea"); ta.value = u; ta.style.position = "fixed"; ta.style.opacity = "0"; document.body.appendChild(ta); ta.select(); document.execCommand("copy"); document.body.removeChild(ta); setCopied(true); setCs(sid); setTimeout(function() { setCopied(false); setCs(0); }, 3000); }
  var btns = SESSIONS.map(function(s) { var ic = copied && cs === s.id; return React.createElement("div", { key: s.id, style: { background: "rgba(255,255,255,0.03)", border: "1px solid #2a2a4a", borderRadius: 14, padding: "14px 18px", marginBottom: 10 } }, React.createElement("div", { style: { display: "flex", alignItems: "center", gap: 14 } }, React.createElement("div", { style: { fontSize: 28 } }, s.emoji), React.createElement("div", { style: { flex: 1 } }, React.createElement("div", { style: { fontSize: 15, fontWeight: 700, color: "#fff" } }, "מפגש " + s.id + ": \"" + s.title + "\""), React.createElement("div", { style: { fontSize: 12, color: "#888" } }, s.sub + " • " + s.slides.length + " שקפים"))), React.createElement("div", { style: { display: "flex", gap: 6, marginTop: 10, flexWrap: "wrap" } }, React.createElement("button", { onClick: function() { p.onStart(s.id); }, style: { flex: "1 1 45%", background: GOLD, color: "#1a1a2e", border: "none", borderRadius: 8, padding: "8px 12px", fontWeight: 700, fontSize: 13, cursor: "pointer" } }, "▶ התחל"), React.createElement("button", { onClick: function() { copyLink(s.id); }, style: { flex: "1 1 45%", background: ic ? "#4CAF50" : "rgba(255,255,255,0.06)", color: ic ? "#fff" : "#aaa", border: "1px solid " + (ic ? "#4CAF50" : "#333"), borderRadius: 8, padding: "8px 12px", fontWeight: 600, fontSize: 13, cursor: "pointer" } }, ic ? "✅ הועתק!" : "🔗 לינק"), React.createElement("button", { onClick: function() { exportHTML(s.id); }, style: { flex: "1 1 45%", background: "rgba(255,255,255,0.03)", color: "#aaa", border: "1px solid #333", borderRadius: 8, padding: "8px 12px", fontSize: 12, cursor: "pointer" } }, "📥 HTML"), React.createElement("button", { onClick: function() { printSession(s.id); }, style: { flex: "1 1 45%", background: "rgba(255,255,255,0.03)", color: "#aaa", border: "1px solid #333", borderRadius: 8, padding: "8px 12px", fontSize: 12, cursor: "pointer" } }, "🖨️ PDF")), ic ? React.createElement("div", { style: { background: "rgba(76,175,80,0.1)", border: "1px solid rgba(76,175,80,0.3)", borderRadius: 8, padding: "6px", marginTop: 6, textAlign: "center" } }, React.createElement("div", { style: { fontSize: 12, color: "#4CAF50" } }, "✅ הלינק הועתק! שלחו בוואטסאפ")) : null); });
  return React.createElement("div", { style: { width: "100%", minHeight: "100vh", background: DARK, fontFamily: "'Segoe UI',sans-serif", direction: "rtl", padding: 20 } }, React.createElement("div", { style: { maxWidth: 600, margin: "0 auto" } }, React.createElement("div", { style: { textAlign: "center", marginBottom: 24 } }, React.createElement("div", { style: { fontSize: 13, color: GOLD, letterSpacing: 2, fontWeight: 700 } }, "🎤 מצב מנחה"), React.createElement("div", { style: { fontSize: 22, fontWeight: 800, color: "#fff", marginTop: 6 } }, "סדנת AI – Comax")), btns));
}

function SlideView(props) {
  var _c = useState(props.initialSlide || 0), cur = _c[0], setCur = _c[1];
  var ses = SESSIONS.find(function(s) { return s.id === props.session; }); var sl = ses.slides; var s = sl[cur]; var isP = props.isP;
  useEffect(function() { if (!isP) return; setState(props.session, cur).catch(function() {}); }, [isP, props.session, cur]);
  useEffect(function() { if (isP) return; function poll() { getState().then(function(d) { if (d && d.length > 0 && d[0].session_id === props.session) setCur(d[0].slide_index); }).catch(function() {}); } poll(); var i = setInterval(poll, 1500); return function() { clearInterval(i); }; }, [isP, props.session]);
  useEffect(function() { if (!isP) return; function h(e) { if (e.key === "ArrowLeft") setCur(function(p) { return Math.min(p + 1, sl.length - 1); }); if (e.key === "ArrowRight") setCur(function(p) { return Math.max(p - 1, 0); }); } window.addEventListener("keydown", h); return function() { window.removeEventListener("keydown", h); }; }, [isP, sl.length]);

  var dotsEl = sl.map(function(_, i) { return React.createElement("div", { key: i, onClick: isP ? function() { setCur(i); } : undefined, style: { width: i === cur ? 18 : 6, height: 6, borderRadius: 3, background: i === cur ? GOLD : "#333", cursor: isP ? "pointer" : "default", transition: "all 0.3s" } }); });

  // PRESENTER: split layout
  if (isP) {
    return React.createElement("div", { style: { width: "100%", height: "100vh", background: DARK, fontFamily: "'Segoe UI',sans-serif", direction: "rtl", display: "flex", flexDirection: "column", overflow: "hidden" } },
      React.createElement("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 14px", flexShrink: 0 } },
        React.createElement("div", { style: { display: "flex", gap: 6, alignItems: "center" } }, React.createElement("div", { style: { fontSize: 11, color: GOLD, fontWeight: 700 } }, "COMAX"), React.createElement("div", { style: { fontSize: 11, color: "#555" } }, "|"), React.createElement("div", { style: { fontSize: 11, color: "#888" } }, "מפגש " + props.session), React.createElement("div", { style: { fontSize: 10, color: "#1a1a2e", background: GOLD, padding: "1px 6px", borderRadius: 4, fontWeight: 700, marginRight: 6 } }, "מנחה")),
        React.createElement("div", { style: { display: "flex", alignItems: "center", gap: 8 } }, React.createElement("div", { style: { fontSize: 11, color: "#555" } }, (cur + 1) + "/" + sl.length), React.createElement("button", { onClick: props.onBack, style: { fontSize: 10, color: "#666", background: "none", border: "1px solid #333", borderRadius: 4, padding: "2px 8px", cursor: "pointer" } }, "🔙 חזרה"))),
      React.createElement("div", { style: { display: "flex", flex: 1, gap: 10, padding: "0 14px 8px", overflow: "hidden" } },
        React.createElement("div", { style: { flex: "0 0 60%", display: "flex", flexDirection: "column", minWidth: 0 } },
          React.createElement("div", { style: { background: "linear-gradient(145deg,#1a1a2e,#16213e)", borderRadius: 12, width: "100%", aspectRatio: "16/9", padding: "24px", boxSizing: "border-box", boxShadow: "0 8px 30px rgba(0,0,0,0.5)", border: "1px solid #2a2a4a", overflow: "hidden", position: "relative" } },
            React.createElement("div", { style: { height: "100%", position: "relative", zIndex: 1, overflow: "auto" } }, s.c)),
          React.createElement("div", { style: { display: "flex", justifyContent: "center", alignItems: "center", gap: 10, marginTop: 6 } },
            React.createElement("button", { onClick: function() { setCur(function(p) { return Math.max(p - 1, 0); }); }, style: { background: cur > 0 ? "rgba(255,255,255,0.1)" : DARK, color: cur > 0 ? "#ccc" : "#333", border: "1px solid #333", borderRadius: 8, padding: "6px 20px", fontSize: 13, fontWeight: 700, cursor: "pointer" } }, "→ הקודם"),
            React.createElement("button", { onClick: function() { setCur(function(p) { return Math.min(p + 1, sl.length - 1); }); }, style: { background: cur < sl.length - 1 ? GOLD : "#333", color: cur < sl.length - 1 ? "#1a1a2e" : "#666", border: "none", borderRadius: 8, padding: "6px 20px", fontSize: 13, fontWeight: 700, cursor: "pointer" } }, "הבא ←")),
          React.createElement("div", { style: { display: "flex", justifyContent: "center", gap: 3, marginTop: 4, flexWrap: "wrap" } }, dotsEl)),
        React.createElement("div", { style: { flex: "0 0 38%", display: "flex", flexDirection: "column", minWidth: 0 } },
          React.createElement("div", { style: { background: "rgba(232,185,49,0.06)", border: "1px solid rgba(232,185,49,0.2)", borderRadius: 12, padding: 14, height: "100%", overflow: "auto", boxSizing: "border-box" } },
            React.createElement("div", { style: { fontSize: 13, color: GOLD, fontWeight: 700, marginBottom: 8, textAlign: "right" } }, "🎤 הערות למנחה:"),
            React.createElement("div", { style: { fontSize: 13, color: "#ccc", lineHeight: 1.8, textAlign: "right", whiteSpace: "pre-wrap", direction: "rtl" } }, s.n || "(אין הערות)")))));
  }

  // VIEWER
  return React.createElement("div", { style: { width: "100%", minHeight: "100vh", background: DARK, fontFamily: "'Segoe UI',sans-serif", direction: "rtl" } },
    React.createElement("div", { style: { width: "100%", maxWidth: 900, margin: "0 auto", padding: "12px 12px 0" } },
      React.createElement("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 } },
        React.createElement("div", { style: { display: "flex", gap: 6, alignItems: "center" } }, React.createElement("div", { style: { fontSize: 11, color: GOLD, fontWeight: 700 } }, "COMAX"), React.createElement("div", { style: { fontSize: 11, color: "#555" } }, "|"), React.createElement("div", { style: { fontSize: 11, color: "#888" } }, "מפגש " + props.session)),
        React.createElement("div", { style: { fontSize: 11, color: "#555" } }, (cur + 1) + "/" + sl.length)),
      React.createElement("div", { style: { background: "linear-gradient(145deg,#1a1a2e,#16213e)", borderRadius: 16, width: "100%", aspectRatio: "16/9", padding: "clamp(16px, 4vw, 36px)", boxSizing: "border-box", boxShadow: "0 16px 50px rgba(0,0,0,0.5)", border: "1px solid #2a2a4a", overflow: "hidden", position: "relative" } },
        React.createElement("div", { style: { height: "100%", position: "relative", zIndex: 1, overflow: "auto" } }, s.c)),
      React.createElement("div", { style: { display: "flex", justifyContent: "center", gap: 4, marginTop: 8, flexWrap: "wrap", paddingBottom: 8 } }, dotsEl)));
}

/* ===== MAIN ===== */
export default function App() {
  var _p = useState(false), isP = _p[0], setIsP = _p[1]; var _s = useState(null), ses = _s[0], setSes = _s[1]; var _v = useState(null), vSes = _v[0], setVSes = _v[1]; var _vs = useState(0), vSl = _vs[0], setVSl = _vs[1];
  var params = typeof window !== "undefined" ? new URLSearchParams(window.location.search) : null;
  var isViewer = params ? params.get("view") === "true" : false;
  useEffect(function() { if (!isViewer) return; function check() { getState().then(function(d) { if (d && d.length > 0 && d[0].session_id > 0) { setVSes(d[0].session_id); setVSl(d[0].slide_index); } else { setVSes(null); } }).catch(function() {}); } check(); var i = setInterval(check, 2000); return function() { clearInterval(i); }; }, [isViewer]);
  function start(id) { setSes(id); setState(id, 0).catch(function() {}); }
  function back() { setSes(null); setState(0, 0).catch(function() {}); }
  if (isViewer) { if (vSes && vSes > 0) return React.createElement(SlideView, { session: vSes, isP: false, onBack: function() {}, initialSlide: vSl }); return React.createElement(WaitingScreen); }
  if (!isP) return React.createElement(LoginScreen, { onLogin: function() { setIsP(true); } });
  if (ses) return React.createElement(SlideView, { session: ses, isP: true, onBack: back });
  return React.createElement(Dashboard, { onStart: start });
}